export type Language = { name: string; code: string; official_name: string }

export const languages: Language[] = [
  { name: 'Bulgarian', code: 'bg', official_name: 'български' },
  { name: 'Chinese (simplified)', code: 'zh-CN', official_name: '简体中文' },
  { name: 'Chinese (traditional)', code: 'zh-TW', official_name: '繁體中文' },
  { name: 'Czech', code: 'cs', official_name: 'čeština' },
  { name: 'Dutch', code: 'nl', official_name: 'Nederlands' },
  { name: 'English (US)', code: 'en-us', official_name: 'English (US)' },
  { name: 'English (UK)', code: 'en-uk', official_name: 'English (UK)' },
  { name: 'Estonian', code: 'et', official_name: 'eesti' },
  { name: 'Finnish', code: 'fi', official_name: 'suomi' },
  { name: 'French', code: 'fr', official_name: 'français' },
  { name: 'German', code: 'de', official_name: 'Deutsch' },
  { name: 'Hungarian', code: 'hu', official_name: 'magyar' },
  { name: 'Japanese', code: 'ja', official_name: '日本語' },
  { name: 'Korean', code: 'ko', official_name: '한국어' },
  { name: 'Latvian', code: 'lv', official_name: 'latviešu' },
  { name: 'Polish', code: 'pl', official_name: 'polski' },
  { name: 'Portuguese (Brazilian)', code: 'pt-BR', official_name: 'português (Brasil)' },
  { name: 'Romanian', code: 'ro', official_name: 'română' },
  { name: 'Russian', code: 'ru', official_name: 'русский' },
  { name: 'Slovenian', code: 'sl', official_name: 'slovenščina' },
  { name: 'Spanish', code: 'es', official_name: 'español' },
  { name: 'Swedish', code: 'sv', official_name: 'svenska' },
  { name: 'Thai', code: 'th', official_name: 'ไทย' },
  { name: 'Turkish', code: 'tr', official_name: 'Türkçe' },
  { name: 'Ukrainian', code: 'uk', official_name: 'українська' },
  { name: 'Greek', code: 'el', official_name: 'Ελληνικά' },
  { name: 'Hebrew', code: 'he', official_name: 'עִבְרִית' },
  { name: 'Kazakh', code: 'kk', official_name: 'қазақ тілі' },
  { name: 'Nepali', code: 'ne', official_name: 'नेपाली' },
  { name: 'Persian', code: 'fa', official_name: 'فارسی' },
]
